# Generated by Django 3.1.3 on 2020-11-13 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TeamName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('abbreviation', models.CharField(max_length=3)),
                ('player', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='biertrofee.player')),
            ],
        ),
    ]
