# Generated by Django 3.1.3 on 2020-11-13 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biertrofee', '0002_poul_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='poule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='poule', to='biertrofee.poul'),
        ),
    ]
